<header>
ようこそ、ゲストさん<br>
<!-- Todo:ゲスト部分の出し分け(未ログイン：ゲスト表示 / ログイン済み：ユーザ名表示)-->
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<!-- add by sofukuda -->
<meta name="keywords" content="オーガニックキッチン,お弁当,配達">
<meta name="description" content="オーガニックキッチンのお弁当配達サイト">
<meta name="viewport" content="width=device-width,initial-scale=1">
<link rel="stylesheet" type="text/css" href="style.css" media="screen">
<script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
<!-- add by sofukuda -->
<a href="/var/www/html/index.html"><img src="http://www.organic-kitchen.co.jp/rogo%20BK.gif" alt="LOGO" width="250" height="100"><br>
旬のお野菜たっぷりのお弁当<br>
<nav>
	<a href="https://www.facebook.com/organic.kitchen.2009">Facebook</a></li>
	<a href="http://ameblo.jp/organic-kitchen">アメブロ</a></li>
	<a href="company.html">企業情報</a></li>
	<a href="user/login.html">ログイン</a></li> or 
	<a href="user/init.html">新規登録</a></li>
	<!-- Todo:ゲスト部分の出し分け(未ログイン：ログイン or 新規登録 / ログイン済み：ログアウト)-->
</nav>
<hr>
</header>
<!-- 以下、body -->
